---
services:
    adguardhome:
        container_name: adguardhome
        image: adguard/adguardhome:v0.107.53
        networks:
          adguardhome:
            ipv4_address: 10.0.0.86  #Change this to a free ip address of the local network
        volumes:
            - CHANGE_TO_COMPOSE_DATA_PATH/adguardhome/workdir:/opt/adguardhome/work
            - CHANGE_TO_COMPOSE_DATA_PATH/adguardhome/confdir:/opt/adguardhome/conf
        restart: unless-stopped
        
networks:
   adguardhome:
      name: xxx-macvlan  #This is the name of our macvlan
      external: true
